// <auto-generated />
namespace HealthTracker.Data.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MoreUserFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoreUserFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201707230439538_MoreUserFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
