//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodEntry
    {
        public System.Guid FoodEntryId { get; set; }
        public System.Guid FoodId { get; set; }
        public System.Guid DiaryId { get; set; }
        public System.Guid MealId { get; set; }
        public int NumberOfServings { get; set; }
        public bool Complete { get; set; }
    
        public virtual Diary Diary { get; set; }
        public virtual Food Food { get; set; }
        public virtual Meal Meal { get; set; }
    }
}
