//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthTrackerEntities : DbContext
    {
        public HealthTrackerEntities()
            : base("name=HealthTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Diary> Diaries { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<ExerciseEntry> ExerciseEntries { get; set; }
        public virtual DbSet<ExerciseGroup> ExerciseGroups { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<FoodEntry> FoodEntries { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<Progress> Progresses { get; set; }
        public virtual DbSet<JoinedFoodEntry> JoinedFoodEntries { get; set; }
        public virtual DbSet<UserDiary> UserDiaries { get; set; }
    }
}
