//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinedFoodEntry
    {
        public System.Guid FoodEntryId { get; set; }
        public System.Guid FoodId { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public System.Guid DiaryId { get; set; }
        public System.DateTime DiaryDate { get; set; }
        public System.Guid MealId { get; set; }
        public string MealName { get; set; }
        public string FoodName { get; set; }
        public double ServingSize { get; set; }
        public string ServingsSizeUnits { get; set; }
        public int NumberOfServings { get; set; }
        public int Calories { get; set; }
        public int Fat { get; set; }
        public int Carbs { get; set; }
        public int Protein { get; set; }
        public int Fiber { get; set; }
    }
}
